version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auctiondb
      MYSQL_USER: ncrmns
      MYSQL_PASSWORD: root
    ports: 
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    build: ./app
    ports: 
      - 1234:1234
    depends_on:
      - db
    # command: sh -c './wait-for db:3306 -- npm start'